services:
  es:
    build: es8
    ports:
      - "19200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - thread_pool.search_worker.size=200
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
  
  #kibana:
  #  image: kibana:8.14.1
  #  environment:
  #    - ELASTICSEARCH_HOSTS=http://es:9200
  #  depends_on:
  #    es:
  #      condition: service_healthy
  #  ports:
  #    - "15601:5601"
  
  cerebro:
    image: lmenezes/cerebro:0.9.4
    ports:
      - "9000:9000"
    depends_on:
      es:
        condition: service_healthy
    environment:
      - JAVA_OPTS=--illegal-access=warn
  
  viewer:
    build: viewer
    ports:
      - "18080:8080"
    depends_on:
      es:
        condition: service_healthy
    environment:
      - JAVA_OPTS=--illegal-access=warn
  
#  ollama:
#    build: ollama
#    ports:
#      - "11434:11434"
#    environment:
#      - MODEL_NAME=gemma2:9b-instruct-q8_0
#      #- MODEL_NAME=llama3
#    volumes:
#      - ./data/ollama:/root/.ollama

  ml-apis:
    build: ml-apis
    ports:
      - "18081:18081"
    environment:
      - HF_ACCESS_TOKEN=
    volumes:
      - ./data/my-apis/cache/huggingface:/root/.cache/huggingface
